config/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    
]

main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns = [
    path('', views.main, name="main"),
    path('<int:question_id>/', views.detail, name="detail"),
    path('answer/create/<int:question_id>/', views.answer_create, name="answer_create"),
    path('question/create/', views.question_create, name="question_create"),
]

main/models.py
from django.db import models

class Question(models.Model):
        subject = models.CharField(max_length=200)
        content = models.TextField()
        create_date = models.DateTimeField()

        def __str__(self):
              return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
# Create your models here.

main/forms.py
from django import forms
from main.models import Question


# ModelForm : model의 db를 연결할 수 있는 form
#               -> Meta라는 inner class 반드시 사용
class QuestionForm(forms.ModelForm): 
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question
from .forms import QuestionForm


def main(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'main/index.html', context)  #reques, 요청한 페이지, 인자

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question':question}
    return render(request, 'main/detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('main:detail', question_id=question.id) 

def question_create(request):
    if request.method == "POST": # post 방식이면
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False) #임시저장
            question.create_date = timezone.now() #create_date 추가
            question.save() # 저장
            return redirect('main:main')
    else: # get 방식이면
        form = QuestionForm()
    context = {"form":form}
    return render(request, 'main/question_form.html', context)

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="vieport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!--bootstrap CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-5.1.3-dist/css/bootstrap.min.css' %}">
        <!--project CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>

    <body>
        {% block content %}
        {% endblock %}
    </body>
</html> 

templates/main/detail.html
{% extends "base.html" %}
{% block content %}

<div class="container my-3">
    <!--질문-->
    <h2 class="border-bottom py-2">{{question.subject}}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{question.content}}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{question.create_date}}
                </div>
            </div>
        </div>
    </div>

    <!--답변-->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all  %}
    <div class ="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{answer.content}}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{answer.create_date}}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <!--답변 등록-->
    <form action="{% url 'main:answer_create' question.id %}" method="POST"  class="my-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="content" class="form-label">답변 내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}           

templates/main/index.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="table-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {% for question in question_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'main:detail' question.id %}">{{ question.subject }}</a>
                </td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <a href="{% url "main:question_create" %}" class="btn btn-primary">질문 등록</a>
</div>
{% endblock %}

templates/main/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="POST">
        {% csrf_token %}
        <!-- 오류 표시 -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 END -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:''}}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:''}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}